---
title: "AnalysisValidation"
author: "Felipe Sodré Mendes Barros"
date: "August 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(sf)
library(raster)
library(pander)
library(tmap)
```

# Analysis Validation

To validate de analysis done with Google Earth Engine, a random study site was selected to have the statistics estimated and compared using R. The buffer was done with a hypotetical 10km radii;

## CEC
### Study site

```{r buffer, warning=FALSE}
buffer <- read_sf("../Data/Buffer_validation.geojson", "Buffer_validation")


tmap_mode("view")
tm_basemap(leaflet::providers$OpenStreetMap) + 
tm_shape(buffer) + 
  tm_borders("black")

```

### Results from GEE
```{r GEEstats}
# reading stats taken from Google Earth Engine
GEEstats <- read.csv("../Data/CECstats.csv")[,c(2,3)]
GEEstats$SudySite <- "Site 269"
GEEstats <- GEEstats[,c(3,1,2)]
pander(GEEstats)
```

### Results from R
```{r Rstats}
# reading stats taken from R
Rstats <- read.csv("./CEC_Rstats.csv")

pander(Rstats)
```

## Slope

```{r, echo=F, warning=F}
# slope analysis
slope <- raster("../Data/ValidationData/slope_test.tif")

site59 <- read_sf("/media/felipe/DATA/Proyectos/SE_EC_MetaAnalysis/Data/Database_18_06_01.shp") %>% 
  dplyr::filter(Site == 59)
site59Buffer <- site59 %>% st_transform(crs = 102033) %>% 
  st_buffer(100000) %>% 
  st_transform(crs = 4326)
slopeMasked <- crop(slope, site59Buffer)
slopeMasked <- mask(slopeMasked, site59Buffer)

compare <- read.csv("/media/felipe/DATA/Proyectos/SE_EC_MetaAnalysis/Scripts/Data/results/Biodiversity_Revision.csv") %>% 
  dplyr::filter(Site == 59) %>% 
  dplyr::select(slope_05Km, slope_10Km, slope_25Km, slope_50Km, slope_75Km, slope_100Km)

# kernel R
#Kernel circular
circular.focal.matrix <- function(cellsize, radius){
  n <- (radius / cellsize) * 2 + 1
  m <- matrix(1, nrow=n, ncol=n)
  a <- (radius / cellsize)
  b <- a + 1
  
  for (i in 1:a){
    for (j in 1:a){
      if (sqrt(i^2 + j^2) > a){
        m[b+i, b+j] <- 0
        m[b+i, b-j] <- 0
        m[b-i, b+j] <- 0
        m[b-i, b-j] <- 0
      }
    }
  }
  return(m)
}

buffers <- c(5, 10, 25, 50, 75, 100)
for (buffer in buffers){
  # buffer <- 10
  kernel <- circular.focal.matrix(1, buffer)
  focalR <- focal(slope, kernel, "sum", na.rm=TRUE) / sum(kernel)
  compare[2, which(buffer==buffers)] <- extract(focalR, site59)
}
compare$tool <- c("GEE", "R")

compare <- compare %>% tidyr::gather(key = "buffer", value = "value", -tool) %>% 
  tidyr::spread(tool, value) %>%
  dplyr::mutate( dif = GEE - R) %>% 
  format(scientific=F)
```
```{r}
pander(compare)
```
```{r}
# map
tm_basemap(leaflet::providers$OpenStreetMap) + 
tm_shape(slopeMasked[[1]], maxpixels = 5000) + 
  tm_raster("slope_test", palette = terrain.colors(10) ) +
  tm_shape(site59Buffer) + 
  tm_dots("black")

```

